ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG CORS_ALLOWS
ENV CORS_ALLOWS=${CORS_ALLOWS}

ARG USER_REPOSITORY_PATH
ENV USER_REPOSITORY_PATH=${USER_REPOSITORY_PATH}

ARG SQLALCHEMY_DATABASE_URL
ENV SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}

ARG SQLALCHEMY_POOL_SIZE
ENV SQLALCHEMY_POOL_SIZE=${SQLALCHEMY_POOL_SIZE}

ARG SQLALCHEMY_POOL_TIMEOUT
ENV SQLALCHEMY_POOL_TIMEOUT=${SQLALCHEMY_POOL_TIMEOUT}

ARG SQLALCHEMY_POOL_RECYCLE
ENV SQLALCHEMY_POOL_RECYCLE=${SQLALCHEMY_POOL_RECYCLE}

ARG SQLALCHEMY_ECHO
ENV SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}

RUN mkdir run data

COPY src/apps/auth/repository/users.json ${USER_REPOSITORY_PATH}

CMD ["python", "-m", "uvicorn", "src.main:app","--host","0.0.0.0","--port","5000"]