# docker는 개발 환경 구축 및 테스트 용도로 사용
version: "3.7"
services:
  base:
    image: ${APP_NAME}-base:latest
    build:
      context: .
      dockerfile: base.Dockerfile
    container_name: base
    command: python3 -V
  app:
    image: ${APP_NAME}:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    hostname: ${APP_NAME}
    container_name: ${APP_NAME}
    # command:
    env_file: ${PWD}/compose.env
    tty: true
    depends_on:
      - "${APP_NAME}-base"
    ports:
      - ${PORT}:${PORT}
    environment:
      - HOST=${HOST}
    volumes:
      - type: bind
        source: ${PWD}/src
        target: /code/src
      - type: bind
        source: ${PWD}/confs
        target: /code/confs
      - type: bind
        source: ${PWD}/run
        target: /code/run
