# docker는 개발 환경 구축 및 테스트 용도로 사용
version: "3.7"
services:
  base:
    image: ${APP_NAME}-base:latest
    build:
      context: .
      dockerfile: base.Dockerfile
    container_name: base
    command: python3 -V
  database:
    image: mysql:8.0
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./infra/mysql.env
    volumes:
      - type: bind
        source: ./infra/init_sql
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./infra/mysql-files
        target: /var/lib/mysql-files
      - type: bind
        source: ./infra/my.cnf
        target: /etc/mysql/my.cnf
  app:
    image: ${APP_NAME}:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    hostname: ${APP_NAME}
    container_name: ${APP_NAME}
    env_file: 
      - ${PWD}/.env
    environment:
      - HOST=${HOST}
      - MYSQL_USER=deo
      - MYSQL_PASSWORD=imdeo
      - MYSQL_ROOT_PASSWORD=imdeo
      - MYSQL_HOST=database
      - MYSQL_DATABASE=todolist
    tty: true
    restart: always
    depends_on:
      - "base"
      - "database"
    ports:
      - ${PORT}:${PORT}

