name: Changelog

on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.20.1]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
      - name: Show current changelog
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm install yarn
          yarn install
          make current_changelog
